services:
  - type: web
    name: cv16-uid-subscription
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"